### ISSUE TITLE
Duplicate Addon

### ISSUE THREAD

**Issue by Panman8201** [vsymguysung/ember-cli-bootstrap-switch#1]
FYI, I'll be publishing another addon that is also for bootstrap-switch. You beat me to the `ember-cli-bootstrap-switch` name so it'll have to be different. Just wanted you to know, not on GitHub just yet but it is done.

**Comment by Panman8201** [comment]
Or, what are your thoughts about a PR with my changes. If so, I'd also like to be listed as an author as the changes would be quite extensive.

**Comment by vsymguysung** [comment]
@Panman8201, Thanks for your suggestions in advance.
PR requests are always welcome and I will look at it.
How do you want me to list you as an author?  Do you want to add your name as an author in README.md or somewhere else?
Anyway, I am really excited about seeing this project gets growing.
Thanks.

**Comment by Panman8201** [comment]
@vsymguysung I actually decided to publish mine separately. Our option names don't line up and you are pull in actual bootstrap files, which is out-of-scope for my addon. Feel free to take a look, I'm still willing to collaborate.

https://github.com/Panman8201/ember-bootstrap-switch

**Comment by vsymguysung** [comment]
No problem at all. I will definitely look at it sometime. thanks.
